### ISSUE TITLE
Design A layout to edit the profile after signin.

### ISSUE THREAD

**Issue by ujjwalagr** [ujjwalagr/Passenger_Security#20]
Expected behavior.

After Google sign in the user must go through to the detailed registration process that is one time and can be editable in future.

Would you like to work on this?

Assigning this to @developershivamshukla

**Comment by developershivamshukla** [comment]
Yes I would like it work on this issue.

**Comment by ujjwalagr** [comment]
Cool

**Comment by ujjwalagr** [comment]
But for This you need a database .
